name: CI workflow
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.0.3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -run=".+UnitTestSuite" ./...

      - name: Integration tests
        run: docker-compose -f docker-compose.test.yml up --exit-code-from medias-server-test
