name: Main CI workflow
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create semantic version
        id: semantic-version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          bump_each_commit: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -run=".+UnitTestSuite" ./...

      - name: Integration tests
        run: docker-compose -f docker-compose.test.yml up --exit-code-from medias-server-test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest, ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.semantic-version.outputs.version }}

      - name: Build artifact
        working-directory: .
        run: go build -o ./${{ env.IMAGE_NAME }}-${{ steps.semantic-version.outputs.version }}.exe ./src/main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}-${{ steps.semantic-version.outputs.version }}
          path: ./${{ env.IMAGE_NAME }}-${{ steps.semantic-version.outputs.version }}.exe
